const logotext = "DEBOJIT";
const meta = {
    title: "Debojit Santra",
    description: "I’m a Jee aspirant and CS student.",
};

const introdata = {
    title: "I’m Debojit Santra",
    animated: {
        first: "I love coding",
        second: "I love math, physics & computer",
        third: "I devolop in c & python ",
    },
    description: ":)",
    your_img_url: "https://images.unsplash.com/photo-1514790193030-c89d266d5a9d",
};

const dataabout = {
    title: "a bit about my self",
    aboutme: "I am a wbchse class 11 student, currently i'm preparing for jee main, as well as advanced to get into my dream college 'IIT KGP'. My goal is to become an AI/ML engineer in future.",
};
const worktimeline = [{
        jobtitle: "Web Developer",
        where: "Urban Rahsoi",
        date: "2023",
    },
    
];

const skills = [{
        name: "Python",
        value: 60,
    },
    {
        name: "C",
        value: 30,
    },
    {
        name: "Prompt Engineering",
        value: 80,
    },
    {
        name: "Cyber Security",
        value: 50,
    },
   /* {
        name: "Jquery",
        value: 85,
    },*/
];

const services = [{
        title: "Python Development",
        description: "Command Line Apps Only",
    },
    {
        title: "Art using AI",
        description: "Realistic and Amazing art can be generated by AI with the help of my prompt engineering skils",
    },
    
];

const dataportfolio = [{
        img: "https://debojitsantra.github.io/debojitsantra2/assets/pro2.jpg",
        description: "A web app to count words",
        link: "https://debojitsantra.github.io/wordcounter",
    },
    {
        img: "https://raw.githubusercontent.com/debojitsantra/debojitsantra2/main/assets/instad.jpg",
        description: "Instagram downloader in python",
        link: "https://debojitsantra.github.io/instad",
    },
    {
        img: "https://debojitsantra.github.io/debojitsantra2/assets/pro3.jpg",
        description: "Port Scanning Tool",
        link: "https://debojitsantra.github.io/itds",
    },
];

const contactConfig = {
    YOUR_EMAIL: "debojits@duck.com",
    description: "Mail me if you want to contact me.",
    // creat an emailjs.com account 
    // check out this tutorial https://www.emailjs.com/docs/examples/reactjs/
    YOUR_SERVICE_ID: "service_i153t6p",
    YOUR_TEMPLATE_ID: "template_676pigl",
    YOUR_USER_ID: "O1zghmCSDpK1qpC4T",
};

const socialprofils = {
    github: "https://github.com/debojitsantra"
    
};
export {
    meta,
    dataabout,
    worktimeline,
    dataportfolio,
    services,
    skills,
    introdata,
    contactConfig,
    socialprofils,
    logotext,
};
